### ISSUE TITLE
upload to mvn central

### ISSUE THREAD

**Issue by fvildoso** [evanrupert/ExcelKt#4]
Hi Evan,

Is it possible to upload this dependency to the central repository?

Can I help you with that?

Regards.

**Comment by evanrupert** [comment]
Hello,

I apologize for my late response.

I am open to uploading this to maven central, but since it seems like a much more complicated process I have a couple of questions.

Why do you recommend the change to maven central?

How would you recommend doing the migration, would we keep it on both jitpack and maven central for the foreseeable future, or set a changeover date or something like that?  I want to make sure this won't disrupt any existing users.

Thanks for your time and interest in the project.

**Comment by fvildoso** [comment]
Hi,

No problem!

I'm involved in a project where we are using your project, and we needed to request special access to add jitpack as a maven repository. So I think it can be useful for future projects if we add this to the maven central.

About your second question, I think we can keep the project in both repositories. Maybe in the future if it costs us too much time, we could choose to keep it in just one repo.

Regards.

**Comment by evanrupert** [comment]
Hello,

Thanks for your response.

I hadn't considered situations like yours, but it makes a lot of sense.

I will start working on getting that uploaded in the next couple of days.  Although it seems to be a slightly involved process, I expect that it will probably be done in a week or so.

I'll update this thread and the readme when I've got it uploaded.

Thanks again for the info.

**Comment by evanrupert** [comment]
Just wanted to give you an update.

I got the project uploaded to maven central and updated the README with the new installation instructions.

Also, I took the time to update the version of Kotlin and apache poi so this new version on maven central may or may not be compatible with your current project.  Nevertheless, the jitpack version should continue to work just fine for existing projects, and new projects can use the maven central version.

Thank you again for bringing this to my attention.  Because of this change, I think the installation process is simpler than before, and the library itself is up-to-date and secure because everything is now running current versions.
