### ISSUE TITLE
Can we use this in KMM project?

### ISSUE THREAD

**Issue by gulabsagevadiya** [evanrupert/ExcelKt#5]
can we use this lib in Kotlin multiplatform with desktop?

**Comment by evanrupert** [comment]
Unfortunately, I am reasonably sure that it would not work on Kotlin multiplatform since ExcelKt depends on the Apache POI library which only runs on the JVM.  It's possible that this could be implemented in the future by using different excel libraries for each of the platforms, but right now I don't really have any plans for this.
